### ISSUE TITLE
Constants XML

### ISSUE THREAD

**Issue by Haldoryn** [Haldoryn/Kartierung-eines-Raums#4]
"speed" = the speed in with the motors are rotating.
"timeout" = the time the protocol waits for a message from the robot till it stops waiting.
"maxScans" = the number of scans the Robot dose in one sweep.
"SensorMoveSpeed" = the speed in with the sensor is rotating.
"AnglePerScan" = the angle in with the robot rotates its sensor per scan.
"RobotIP" = the IP of the robot.
"RobotPort" = the port of the robot.
"wheelDistance" = the distance between the wheels.
"wheelRadius" = the radius of the wheels.
"distancePerMove" = the distance the robot moves per move.

**Comment by Jan-Malte-W** [comment]
Renamed Class and Packaged. Added Constants to File. TODO: Path

**Comment by Haldoryn** [comment]
can you push the changes?

**Comment by Jan-Malte-W** [comment]
Done and pushed
